include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    camel_case_types: ignore
    must_be_immutable: ignore
    override_on_non_overriding_member: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
